"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.db = void 0;
const mongodb_1 = require("mongodb");
require("dotenv/config");
const uri = process.env.MONGO_URI;
const databaseName = process.env.DATABASE_NAME;
const client = new mongodb_1.MongoClient(uri);
exports.db = client.db(databaseName);
// export const db = client.db("moral_panic_bot");
